class LLMService:
    """
    LLM abstraction.

    This local implementation returns a grounded demo response.
    For production, connect this class to OpenAI, Azure OpenAI, AWS Bedrock, or local LLMs.
    """

    def generate_answer(self, question: str, context: str) -> str:
        if not context.strip():
            return "I could not find enough relevant context in the knowledge base."

        return (
            "Based on the retrieved enterprise knowledge context, here is a grounded answer:\n\n"
            f"Question: {question}\n\n"
            f"Relevant Context Summary:\n{context[:1200]}\n\n"
            "Note: In production, this response would be generated by a configured LLM provider "
            "with citations, access control, and audit logging."
        )
